package org.jbpm.dependencia;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(e2647fdede2a4e9539f09b204bcac954)
 */
public class Owner  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer age;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String name;
    
    @org.kie.api.definition.type.Position(value = 2)
    private org.jbpm.test.Animal pet;

    public Owner() {
    }

    public Owner(java.lang.String name, java.lang.Integer age, org.jbpm.test.Animal pet) {
        this.name = name;
        this.age = age;
        this.pet = pet;
    }


    
    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public org.jbpm.test.Animal getPet() {
        return this.pet;
    }

    public void setPet(org.jbpm.test.Animal pet) {
        this.pet = pet;
    }
}